// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: databus-serv.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DatabusServiceClient is the client API for DatabusService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DatabusServiceClient interface {
	// !< Sends data to the bus.
	Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error)
}

type databusServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDatabusServiceClient(cc grpc.ClientConnInterface) DatabusServiceClient {
	return &databusServiceClient{cc}
}

func (c *databusServiceClient) Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error) {
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, "/databusService.DatabusService/send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DatabusServiceServer is the server API for DatabusService service.
// All implementations must embed UnimplementedDatabusServiceServer
// for forward compatibility
type DatabusServiceServer interface {
	// !< Sends data to the bus.
	Send(context.Context, *SendRequest) (*SendResponse, error)
	mustEmbedUnimplementedDatabusServiceServer()
}

// UnimplementedDatabusServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDatabusServiceServer struct {
}

func (UnimplementedDatabusServiceServer) Send(context.Context, *SendRequest) (*SendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedDatabusServiceServer) mustEmbedUnimplementedDatabusServiceServer() {}

// UnsafeDatabusServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DatabusServiceServer will
// result in compilation errors.
type UnsafeDatabusServiceServer interface {
	mustEmbedUnimplementedDatabusServiceServer()
}

func RegisterDatabusServiceServer(s grpc.ServiceRegistrar, srv DatabusServiceServer) {
	s.RegisterService(&DatabusService_ServiceDesc, srv)
}

func _DatabusService_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabusServiceServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/databusService.DatabusService/send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabusServiceServer).Send(ctx, req.(*SendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DatabusService_ServiceDesc is the grpc.ServiceDesc for DatabusService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DatabusService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "databusService.DatabusService",
	HandlerType: (*DatabusServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "send",
			Handler:    _DatabusService_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "databus-serv.proto",
}
